<?php include('assets/inc/header.php');
include('functions.php');
$currentMonth = date('F'); ?>

<div class="wrapper report-sighting">
<form method="post" id="sightingForm">
    <div class="row">
        <div class="col-lg-3">
            <fieldset class="small">
                <legend>#1</legend>
                <label class="fieldset-label">Upload sighting photos</label>
                <small>If you have an image of the Swallow-Tailed Kite, you can upload it here.</small>
                <button class="btn btn-primary btn-sm btn-block" data-toggle="modal" data-target="#myModal">Upload!</button>
            </fieldset>
        </div>
        <div class="col-lg-3">
            <fieldset class="small">
                <legend>#2</legend>
                <label class="fieldset-label">Plot Sighting Location</label>
                <small>To pinpoint the exact location of the sighting, drag the pin to the nearest possible spot.</small>
                <button class="btn btn-primary btn-sm btn-block" data-toggle="modal" id="googleModal">Plot!</button>
            </fieldset>
        </div>
        <div class="col-lg-6">
            <fieldset class="small">
                <legend>#3</legend>
                <label class="fieldset-label">Automatically generated values</label>
                <small>All values in these boxes are generated by the previous two steps. </small>
                <div class="row">
                    <div class="form-group col-lg-4">
                        <label>Image Link:</label>
                        <input type="text" value="" name="imageLink" id="imgurLink" class="form-control" readonly/>
                    </div>
                    <div class="form-group col-lg-4">
                        <label>Latitude:</label>
                        <input type="text" id="locationLat" class="form-control" name="sightingLat" value="" readonly/>
                    </div>
                    <div class="form-group col-lg-4">
                        <label>Longitude:</label>
                        <input type="text" id="locationLng" class="form-control" name="sightingLng" value="" readonly/>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <fieldset>
                <legend>#4</legend>
                <label class="fieldset-label">Sighting Date</label>
                  <div class="row">
                    <div class="form-group col-lg-6">
                        <label>Month:</label>
                        <select name="month" class="form-control input-sm">
                            <?php for ($m = 1; $m <= 12; $m++) {
                            $month = date("F", mktime(0, 0, 0, $m));
                            if ($currentMonth === $month) {
                                $selected = "selected";
                            } else {
                                $selected = "";
                            }
                            ;
                            echo "<option value='$m' " . $selected . "> $month</option>";
                        }?>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                        <label>Date:</label>
                        <select name="day" class="form-control input-sm">
                            <?php $currentDate = date('j');
                            $currentMonth = get_day_number($currentMonth); for ($m = 1; $m <= $currentMonth; $m++) {
                            if ($currentDate == $m) {
                                $sel = "selected";
                            } else {
                                $sel = '';
                            }
                            ;
                            echo "<option value='$m' " . $sel . ">$m</option>";
                        }?>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                        <label>Year:</label>
                        <?php $year = str_replace('20', '', date('Y')); $endyear = $year + 10;?>
                        <select name="year" class="form-control input-sm">
                            <?php  for ($m = $year; $m <= $endyear; $m++) {
                            echo "<option value='20$m' >20$m</option>";
                        }?>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                        <label>Time:</label>
                        <select name="sightingTime" class="form-control input-sm">
                            <?php  for ($m = 1; $m <= 12; $m++) {
                            echo "<option value='$m'>$m:00 am</option>";
                        }
                            for ($m = 1; $m <= 12; $m++) {
                                echo "<option value='$m'>$m:00 pm</option>";
                            }?>
                        </select>
                    </div>
                  </div>
                    <label class="fieldset-label">Area</label>
                  <div class="row">
                    <div class="form-group col-lg-6">
                        <label>State:</label>
                        <select name="state" class="form-control input-sm">
                            <option value="Alabama"> Alabama </option>
                            <option value="Alaska"> Alaska </option>
                            <option value="Arizona"> Arizona </option>
                            <option value="Arkansas"> Arkansas </option>
                            <option value="California"> California </option>
                            <option value="Colorado"> Colorado </option>
                            <option value="Connecticut"> Connecticut </option>
                            <option value="Delaware"> Delaware </option>
                            <option value="Florida"> Florida </option>
                            <option value="Georgia"> Georgia </option>
                            <option value="Hawaii"> Hawaii </option>
                            <option value="Idaho"> Idaho </option>
                            <option value="Illinois"> Illinois </option>
                            <option value="Indiana"> Indiana </option>
                            <option value="Iowa"> Iowa </option>
                            <option value="Kansas"> Kansas </option>
                            <option value="Kentucky"> Kentucky </option>
                            <option value="Louisiana"> Louisiana </option>
                            <option value="Maine"> Maine </option>
                            <option value="Maryland"> Maryland </option>
                            <option value="Massachusetts"> Massachusetts </option>
                            <option value="Michigan"> Michigan </option>
                            <option value="Minnesota"> Minnesota </option>
                            <option value="Mississippi"> Mississippi </option>
                            <option value="Missouri"> Missouri </option>
                            <option value="Montana"> Montana </option>
                            <option value="Nebraska"> Nebraska </option>
                            <option value="Nevada"> Nevada </option>
                            <option value="New Hampshire"> New Hampshire </option>
                            <option value="New Jersey"> New Jersey </option>
                            <option value="New Mexico"> New Mexico </option>
                            <option value="New York"> New York </option>
                            <option value="North Carolina"> North Carolina </option>
                            <option value="North Dakota"> North Dakota </option>
                            <option value="Ohio"> Ohio </option>
                            <option value="Oklahoma"> Oklahoma </option>
                            <option value="Oregon"> Oregon </option>
                            <option value="Pennsylvania"> Pennsylvania </option>
                            <option value="Rhode Island"> Rhode Island </option>
                            <option value="South Carolina"> South Carolina </option>
                            <option value="South Dakota"> South Dakota </option>
                            <option value="Tennessee"> Tennessee </option>
                            <option value="Texas"> Texas </option>
                            <option value="Utah"> Utah </option>
                            <option value="Vermont"> Vermont </option>
                            <option value="Virginia"> Virginia </option>
                            <option value="Washington"> Washington </option>
                            <option value="West Virginia"> West Virginia </option>
                            <option value="Wisconsin"> Wisconsin </option>
                            <option value="Wyoming"> Wyoming </option>
                        </select>
                    </div>
                    <div class="form-group col-lg-6">
                        <label>County:</label>
                        <input type="text" name="" placeholder="" class="form-control input-sm" data-regex="^[a-z0-9 ]+"/>
                    </div>
                  </div>

                    <div class="form-group">
                        <label>Please give a description of the area where the Kite was seen.</label>
                        <textarea class="form-control" name="area-description" data-regex="^[a-zA-Z0-9 -!?]+$"></textarea>
                    </div>
            </fieldset>
        </div>
        <div class="col-lg-4">
            <fieldset>
                <legend>#5</legend>
                <label class="fieldset-label">Quantitative Measurements</label>
                <div class="form-group">
                    <label>Number of Kites seen:</label>
                    <select name="numberSpotted" class="form-control input-sm">
                        <?php  for ($m = 1; $m <= 20; $m++) {
                        echo "<option value='$m'>$m</option>";
                    } ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Was a <a href="#" class="infoWindow" data-toggle="popover" title="Swallow-tailed Kite nest" data-content="This is a swallow-tailed Kite nest">nest</a> observed?</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="0"/>
                        Yes</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="1"/>
                        No</label>
                </div>
                <div class="form-group">
                    <label>Have you seen the kites more than once?</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="0"/>
                        Yes</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="1"/>
                        No</label>
                </div>
                <div class="form-group">
                    <label>Did your sighting occur during the SC Audubon boat survey?</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="0"/>
                        Yes</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="1"/>
                        No</label>
                </div>
                <div class="form-group">
                    <label>Did the observation occur on your property?</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="1" onclick="showAcres(1);"/>Yes</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="0" onclick="showAcres(0);"/> No</label>
                    <div class="form-group" id="showAcres" style="display:none;">
                        <label>How many acres do you manage?</label>
                        <input type="number" name="acres-managed" class="form-control input-sm"/>
                    </div>
                </div>
            </fieldset>

        </div>
        <div class="col-lg-4">
            <fieldset>
                <legend>#6</legend>
                <label class="fieldset-label">Details</label>
                <div class="form-group">
                    <label>What was the bird doing? <small>(check all that apply)</small> </label>
                    <ul class="multi">
                        <li><input type="checkbox" name="vehicle" value="Soaring"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Soaring!" data-content="This bird is Soaring">Soaring</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Perching"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Perching"  data-content="This bird is perching">Perching</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Carry Nest Materials"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Perching" data-content="Carrying Nest Materials (sticks, Spanish Moss)">Carrying
                                Nest Materials (sticks, Spanish Moss)</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Vocalizing"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Perching" data-content="This bird is Vocalizing">Vocalizing</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Vocalizing"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Perching" data-content="This bird is Flapping">Flapping</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Foraging over open Habitat"/>
                            <label><a href="#"  class="infoWindow" data-toggle="popover" title="Perching" data-content="This bird is Foraging over open habitat">Foraging
                                over open habitat</a></label>
                        </li>
                        <li><input type="checkbox" name="vehicle" value="Foraging over forest"/>
                            <label><a href="#" class="infoWindow" data-toggle="popover" title="Perching" data-content="This bird is Foraging over forest habitat ">Foraging
                                over forest habitat </a></label>
                        </li>
                    </ul>
                </div>
                <div class="form-group">
                    <label>Would you be interested in hearing more about managing your land for Swallow-tailed Kites?</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="0"/>
                        Yes</label>
                    <label class="radio-inline">
                        <input type="radio" name="nestObserved" value="1"/>
                        No</label>
                </div>
                <div class="form-group">
                    <label>Additional Comments, such as what the kites doing:</label>
                    <textarea class="form-control" name="additional-comments" data-regex="^[a-zA-Z0-9 -!?]+"></textarea>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="row">
        <div class=" col-lg-12">
          <fieldset>
              <legend>#7</legend>
              <label class="fieldset-label">User Information</label>
              <div class="row">
                 <div class="form-group col-lg-3">
                     <label>First Name:</label>
                     <input type="text" name="FirstName" class="form-control input-sm" data-regex="^[a-z -]+" />
                 </div>
                  <div class="form-group col-lg-3">
                      <label>Last Name:</label>
                      <input type="text" name="LastName" class="form-control input-sm" data-regex="^[a-z -]+" />
                  </div>
                  <div class="form-group col-lg-3">
                      <label>Email:</label>
                      <input type="email" name="Email" class="form-control input-sm" data-regex="^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$"/>
                  </div>
                  <div class="form-group col-lg-3">
                      <label>Phone:</label>
                      <input type="tel" name="Email" class="form-control input-sm" data-regex="^[2-9]\d{2}-\d{3}-\d{4}$" />
                  </div>
              </div>
              <div class="row">
                  <div class="form-group col-lg-5">
                      <label>Address:</label>
                      <input type="text" name="Email" class="form-control input-sm" data-regex="^[a-z0-9 ,_-]+"/>
                  </div>
                  <div class="form-group col-lg-3">
                      <label>City:</label>
                      <input type="text" name="Email" class="form-control input-sm" data-regex="^[a-z -]+"/>
                  </div>
                  <div class="form-group col-lg-2">
                      <label>State:</label>
                      <select name="state" class="form-control input-sm">
                          <option value="Alabama"> Alabama </option>
                          <option value="Alaska"> Alaska </option>
                          <option value="Arizona"> Arizona </option>
                          <option value="Arkansas"> Arkansas </option>
                          <option value="California"> California </option>
                          <option value="Colorado"> Colorado </option>
                          <option value="Connecticut"> Connecticut </option>
                          <option value="Delaware"> Delaware </option>
                          <option value="Florida"> Florida </option>
                          <option value="Georgia"> Georgia </option>
                          <option value="Hawaii"> Hawaii </option>
                          <option value="Idaho"> Idaho </option>
                          <option value="Illinois"> Illinois </option>
                          <option value="Indiana"> Indiana </option>
                          <option value="Iowa"> Iowa </option>
                          <option value="Kansas"> Kansas </option>
                          <option value="Kentucky"> Kentucky </option>
                          <option value="Louisiana"> Louisiana </option>
                          <option value="Maine"> Maine </option>
                          <option value="Maryland"> Maryland </option>
                          <option value="Massachusetts"> Massachusetts </option>
                          <option value="Michigan"> Michigan </option>
                          <option value="Minnesota"> Minnesota </option>
                          <option value="Mississippi"> Mississippi </option>
                          <option value="Missouri"> Missouri </option>
                          <option value="Montana"> Montana </option>
                          <option value="Nebraska"> Nebraska </option>
                          <option value="Nevada"> Nevada </option>
                          <option value="New Hampshire"> New Hampshire </option>
                          <option value="New Jersey"> New Jersey </option>
                          <option value="New Mexico"> New Mexico </option>
                          <option value="New York"> New York </option>
                          <option value="North Carolina"> North Carolina </option>
                          <option value="North Dakota"> North Dakota </option>
                          <option value="Ohio"> Ohio </option>
                          <option value="Oklahoma"> Oklahoma </option>
                          <option value="Oregon"> Oregon </option>
                          <option value="Pennsylvania"> Pennsylvania </option>
                          <option value="Rhode Island"> Rhode Island </option>
                          <option value="South Carolina"> South Carolina </option>
                          <option value="South Dakota"> South Dakota </option>
                          <option value="Tennessee"> Tennessee </option>
                          <option value="Texas"> Texas </option>
                          <option value="Utah"> Utah </option>
                          <option value="Vermont"> Vermont </option>
                          <option value="Virginia"> Virginia </option>
                          <option value="Washington"> Washington </option>
                          <option value="West Virginia"> West Virginia </option>
                          <option value="Wisconsin"> Wisconsin </option>
                          <option value="Wyoming"> Wyoming </option>
                      </select>
                  </div>
                  <div class="form-group col-lg-2">
                      <label>Zip Code:</label>
                      <input type="text" name="Email" class="form-control input-sm" data-regex="^\d{5}$" />
                  </div>

              </div>
          </fieldset>
        </div>
    </div>
    <div class="sighting-submit">
        <button class="btn btn-primary btn-lg" id="submitSighting">Submit</button>
    </div>
</form>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Upload Sighting Photos</h4>
            </div>
            <div class="alert alert-full" id="UploadError" style="display:none;"></div>
            <div class="modal-body">
                <div id="main">
                    <form method="post" enctype="multipart/form-data" id="imageUpload">
                        <input type="file" name="images" id="fileInput" class="form-control input-sm" style="display:inline-block; width:80%;">
                        <button type="submit" class="btn btn-default btn-sm pull-right" id="uploadImageBtn">Upload
                            Image </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="locationPicker" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirm Sighting location</h4>
            </div>
            <div class="modal-body"> <small>To show the location of the sighting, click and drag the marker to the closest point possible to
                the sighting. Latitude and Longitude values will automatically be saved off. </small>
                <div id="map-canvas"
                     style="width:100%; height:350px; margin-top:10px; border:1px solid #ddd; display:block;"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btn-block" data-dismiss="modal" aria-hidden="true">Done </button>
            </div>
        </div>
    </div>
</div>

<script>

    jQuery(document).on('click', '#googleModal', function () {
        jQuery('#locationPicker').modal('show');
    });

    jQuery('#locationPicker').on('shown.bs.modal', function () {
        initialize();
    });

    function showAcres(num) {

        if (num == 1) {
            jQuery('#showAcres').slideDown();
        } else {
            jQuery('#showAcres').slideUp();
            return false;
        }
    }

    jQuery('#sightingForm').submit(function(event){
      event.preventDefault();
      var form = jQuery('#sightingForm');
      form.find('input[type="text"], textarea, input[type="email"]').each(function(){
         var input = jQuery(this);
         input.parent().removeClass('has-error');
         var regex = jQuery(this).attr('data-regex'); console.log(regex);
         if(regex){
             var value = input.val(); console.log(value)
             var regexObj = new RegExp(regex, 'i'); console.log(regexObj);
             var outcome = regexObj.test(value); console.log(outcome);
             if(outcome == false){
                 throw_input_error(input);
             }
         }
      });
        submit_sighting(form);
    });

    function  throw_input_error(input){ console.log(input.parent());
        input.parent().addClass('has-error');
    }

    function submit_sighting(form){
        var formData = form.serialize(); console.log(formData);
        /*jQuery.ajax({
          SEND FOR DATA TO PHP SCRIPT
        }) */
    }

    jQuery('#imageUpload').submit(function (event) { // CATCH FORM SUBMIT
        // PREVENT DEFAULT FORM FUNCTIONALITY
        event.preventDefault();
        // DEFINE FORM
        var form = jQuery(this);
        // FORM BUTTON
        var formBtn = form.find('button#uploadImageBtn');
        // DISABLE FORM BUTTON WHILE UPLOADING
        //formBtn.text('Hello...').prop('disabled', true).prepend('<img src="http://www.bba-reman.com/images/fbloader.gif" alt=""/>');
        // GET FORMDATA FOR IMAGES TO SEND TO PHP SCRIPT
        var formData = new FormData(form[0]);
        // CALL AJAX AND POST DATA FROM FORM - RETURN VALUE IS A JSON STRING FROM IMGUR
        var uploadError = jQuery('#UploadError');
        // CREATE DIV FOR UPLOADED IAMGE
        var imageField = '<div id="imgContainer"></div>';
        // REMOVE ALL CLASSES FROM UPLOAD ERROR DIV
        uploadError.removeClass('alert-danger').removeClass('alert-success');
        // DELETE IMG FIELD AND CLEAR ALL HTML OUT OF IT
        jQuery('#imgContainer').html('').remove();
        // START AJAX FUNCTION TO PUSH IMAGE DATA TO IMGUR PHP SCRIPT
        jQuery.ajax({
            url:'assets/scripts/upload.php',
            type:'POST',
            data:formData,
            async:false,
            headers : { "cache-control": "no-cache" }, // MUST HAVE CACHE BUSTER FOR IOS 6
            success:function (imgurData) { // REGARDLESS OF WHAT IT IS, THERE WILL BE A RESPONSE
                // PARSE RESPONSE INTO JSON FORMAT
                var imgurData = JSON.parse(imgurData); //alert(imgurData.success);

                if (imgurData.success == true) { // IF JSON OBJECT RETURNS TRUE, THEN IMGUR SENT THE RESPONSE
                    // BIND IMGUR LINK TO UPLOADED IMAGE - WILL BE STORED IN DATABASE
                    var imgLink = imgurData.data.link;
                    // APPEND NEWLY UPLOADED IMAGE TO A SPOT IN THE CURRENT APP TO LET THE USER KNOW IT WAS GOOD
                    form.append(imageField);
                    jQuery('#imgContainer').append('<img src="' + imgLink + '" style="width:100%; height:100%;" alt=""/>');
                    uploadError.html('<p>Upload Successful!</p>').addClass('alert-success').slideDown();
                    //formBtn.html('Upload Image').prop('disabled', false);
                    jQuery('#imgurLink').val(imgLink);
                    form.trigger('reset');
                } else { // HANDLE ANY ERRORS THROWN  imgurData.data.size + ' '
                    uploadError.html('<p>'+ imgurData.success + '</p>').addClass('alert-danger').slideDown();
                    //formBtn.html('Upload Image').prop('disabled', false);
                }
            },
            cache:false,
            contentType:false,
            processData:false
        });
    });

    jQuery('a.infoWindow').popover({
        animation:true,
        placement:'bottom',
        trigger:'hover'
    });


    function supports_html5_storage() {
        try {
            return 'localStorage' in window && window['localStorage'] !== null;
        } catch (e) {
            return false;
        }
    }


    function initialize() {
        // CHECK FOR LOCAL STORAGE
        var storage = supports_html5_storage();
        // IF STORAGE ASSUME THERE IS A SET OF STORED COORDINATES
        if (storage == false) {
            var lat = localStorage.getItem('storedLatitude');
            var lng = localStorage.getItem('storedLongitude');
        } else { // ELSE ASSUME THERE IS A COOKIE WITH JSON OBJECT OF COORDINATES
            var cookieCoords = JSON.parse(jQuery.cookie('Kite_Tracker_Coordinates'));
            var lat = cookieCoords.lat;
            var lng = cookieCoords.lng;
        }
        // TAKE VALUES FROM EITHER LOCAL STORAGE OR COOKIE AND TURN THEM INTO COORDINATES TO RENDER MAP FROM
        var coords = new google.maps.LatLng(lat, lng);
        // TAKE LAT AND LONG VALUES AND ADD THEM TO INPUTS FOR FORM SUBMISSION
        jQuery('#locationLat').val(lat);
        jQuery('#locationLng').val(lng);
        // DEFINE MAP OPTIONS
        var mapOptions = {
            center:coords,
            zoom:12,
        };
        // DEFINE MAP WITH OPTIONS AND BIND TO CONTAINER
        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

        // DEFINE A DRAGGABLE MARKER
        var marker = new google.maps.Marker({
            position:coords,
            map:map,
            animation:google.maps.Animation.DROP,
            draggable:true,
            title:'Draggable Coordinate Picker'
        });
        // LISTEN FOR MARKER DRAG AND UPDATE COORDINATES IN FORM FIELDS ON DRAG
        google.maps.event.addListener(marker, 'drag', function (event) {
            var lat = event.latLng.lat();
            var lng = event.latLng.lng();
            jQuery('#locationLat').val(lat);
            jQuery('#locationLng').val(lng);
        });

    }


</script>
<?php include('assets/inc/footer.php'); ?>
